### ISSUE TITLE
"Start application" does not import icon

### ISSUE THREAD

**Issue by PhoenixWyllow** [SuchByte/Macro-Deck-Windows-Utils-Plugin#15]
https://user-images.githubusercontent.com/54237626/151696824-3b1778a8-9cc0-480a-8389-0594996d93c2.mp4

Expected behaviour:
the prompt used to work where the user could choose the icon pack in which to add the icon.

Possible additional improvement:
the possibility of creating a new icon pack when importing the icon.

**Comment by PhoenixWyllow** [comment]
I recompiled the current code on my pc and it works ok...?

**Comment by SuchByte** [comment]
Fixed with v.1.4.1
